export class AboutTranslate{
    
    static languagesWords:Array<any>=[
       
        {sr:{
            header_big_text:"Naš fokus je u detaljima",
            header_underline_text:"Naša vizija je da",
            header_underline_text2:"kvalitetnom i profesionalnom",
            header_underline_text3:"uslugom pomognemo našim klijentima da naprave značajna i dugotrajna poboljšanja u svom biznisu. Uvek se trudimo da klijent koji ostvaruje saradnju sa nama",
            header_underline_text4:"bude zadovoljan",
            header_underline_text5:"i proširi lični",
            header_underline_text6:"biznis na veći nivo",
            header_underline_text7:"sajtom koji izgleda savršeno I uliva poverenja potencijalnim klijentima.",
            card_text:"Naš kvalitet",
            card_text_under:"Mi razvijamo vaše ideje iz snova do stvarnosti",
            card1:"Veliki broj zadovoljnih klijenata koji su sarađivali sa nama",
            card2:"Mi garantujemo najviši kvalitet vaših projekata",
            card3:"Potrudićemo se da odgovorimo na vaše zahteve što je pre moguće",
            card4:"Uvek dostupni klijentima",
            biography_text:"Lični podaci",
            biography_text2:"Biografija",
            biography_text3:"O meni.",
            biography_text4:"Ime",
            biography_text5:"Prezime",
            biography_paragraph:"Moje ime je Aleksa Lukić, trenutno sam student druge godine softverskog inžinjerstva na Univerzitetu Metropolitan. Zahvaljujući savremenom programu i individualnom trudu, stekao sam potrebna znanja za izradu modernih web sajtova i web aplikacija koje možete videti u galeriji radova uspešno sam savladao",
            biography_paragraph2:"Javu",
            biography_paragraph3:"do nivoa da mogu da napravim aplikacije za kompanije koje olakšavaju rad. Iznad i savladao sam ",
            biography_paragraph4:"MySQL,NodeJS,Angular",
            biography_paragraph5:"takođe.",
            header_project_text:"Neki od projekata",
            under_header_project_text:"Daćemo sve od sebe da Vaš projekat izgleda moderno, unikatno",
            under_header_project_text2:"i iznad konkurencije.",
            header_impression_text:"Utisci klijenata",
            impression_paragraph:"Uverite se i sami u zadovoljne",
            impression_paragraph2:"utiske naših klijenata",
            biography_marko:"Zdravo,",
            biography2_marko:"Ja sam Marko!",
            biography3_marko:", Imam 20 godina i potrebno znanje za",
            biography4_marko:"Web programiranje.",
            biography5_marko:"Živim u ",
            biography6_marko:"Srbiji.",
            biography7_marko:"Posle srednje škole, upisao sam Informacione Tehnologije na Univerzitetu Metropolitan, gde i dalje studiram. Kroz godinu dana kreirao sam veliki broj prostih HTML & CSS web sajtova pracenim grafiickim dizajnom. Posle godinu dana rada krenuo sam da učim naprednije web tehnologije. Tehnologije koje sam naučio su:",

            biography8_marko:"JavaScript, Angular, i PHP.",
            biography9_marko:"Zajedno sa kolegom i našim timom, potrudićemo se da sve vaše želje pretvorimo u stvarnost i dovedemo Vas korak ispred konkurencije.",
            sidebar_text1:"Početna",
            sidebar_text2:"O nama",
             sidebar_text3:"Naruči",
             sidebar_text4:"Tehnička podrška",
             sidebar_text5:"Ko smo mi?",
             sidebar_text6:"Projekti",
             sidebar_text7:"Utisci klijenata",
             sidebar_text8:"Kontakt",
             

        }

        ,en:{
            header_big_text:"We focus on detail",
            header_underline_text:"Our vision is to provide ",
            header_underline_text2:"quality and professional",
            header_underline_text3:"service to our clients to make significant and lasting improvements in their businesses. We always try to make the client who cooperates with us",
            header_underline_text4:"happy",
            header_underline_text5:"and expands personal",
            header_underline_text6:"business to a greater level",
            header_underline_text7:"with a site that looks perfect and instills confidence in potential clients.",
            card_text:"Our quality",
            card_text_under:" We develop your ideas from dreams to the real one ",
            card1:"A large number of satisfied clients who have cooperated with us",
            card2:"We guarantee the highest quality of your projects",
            card3:"We will do our best to respond to your requests as soon as possible",
            card4:"Always available for clients",
            biography_text:"Personal data",
            biography_text2:"Biography",
            biography_text3:"About me.",
            biography_text4:"Name",
            biography_text5:"Last Name",
            biography_paragraph:"My name is Aleksa Lukić and I'm currently student of the second year of the Metropolitan University,software engineering. Thanks to a modern program and individual effort, I gained the necessary knowledge to create modern websites and web application that you can see in gallery of works, and I have successfully mastered",
            biography_paragraph2:"Java",
            biography_paragraph3:"to the level that I can make applications for companies that make work easier. Over and above, I've mastered",
            biography_paragraph4:"MySQL,NodeJS,Angular",
            biography_paragraph5:"too.",
            

            header_project_text:"Some of the project",
            under_header_project_text:"We will do our best to make your project look modernunique and ",
            under_header_project_text2:"above the competition",
            header_impression_text:"Customer Impressions",
            impression_paragraph:"See for yourself the satisfied",
            impression_paragraph2:"impressions of our clients",
            biography_marko:"Hi,",
            biography2_marko:"I’m Marko!",
            biography3_marko:", I’m 20 years old, self-taught",
            biography4_marko:"Web Developer",
            biography5_marko:", from",
            biography6_marko:"Serbia",
            biography7_marko:" After my high school, I enrolled in information technology at Metropolitan University, where  I continue to study. For whole year I create high number simple HTML & CSS websites following given designs. After a year of working, I started learning more advanced web programming technologies. The technologies that I learned:",
            biography8_marko:"JavaScript, Angular, and PHP.",
            biography9_marko:" Together, me, my colleague and our team, we will do our best to turn all your wishes into reality and bring you one step ahead of the competition.",
            sidebar_text1:"Home",
            sidebar_text2:"About",
            sidebar_text3:"Order",
            sidebar_text4:"Technical Support",
            sidebar_text5:"Who are we?",
            sidebar_text6:"Projects",
            sidebar_text7:"Impressions",
            sidebar_text8:"Contact Form",
            
        }}


    ]
}
