export class HomeTranslate{

   static languagesWords:Array<any>=[
       
        {sr:{
            header_big_text:"Naš fokus je u detaljima",
            header_underline_text:"Vaše ideje postaju stvarnost",
            header_btn:"Više informacija",
            four_card_h1:"Budi profesionalan",
            four_card_paragraf_fp:"Budi u toku i",
            four_card_paragraf_span:" unapredi svoj biznis",
            four_card_paragraf_sp:" profesionalnim vebsajtom",
            code_card_fp:"Koristimo najnovije tehnologije",
            code_card_sp:" prilikom izrade proizvoda",
            modern_design_card:"Izrada veb stranica modernog dizajna",
            relationship_card:"Odlična saradnja sa klijentima",
            production_card_fp:"Produkcija vaših sajtova",
            production_card_sp:" u rekordnom roku",
            about_div:"o nama",
            about_paragraf_fp:"Mi smo tim profesionalaca koji se bavi profesionalnom izradom",
            about_paragraf_span1:" veb aplikacija,",
            about_paragraf_span2:"prezentacijskih sajtova",
            about_paragraf_sp:"i drugih IT usluga.",
            about_paragraf_tp:" Više o tome na stranici o nama.",
            about_div_btn:"Više o nama",
            skill_header:"Veštine",
            pricing_header:"Paketi održavanja",
            pricing_paragraf_fp:"Kako bi Vaša veb aplikacija ili stranica",
            pricing_paragraf_span:" bila dobro pozicionirana",
            pricing_paragraf_sp:"i na pravilan način konstantno funkcionisala,neophodno joj je održavanje.",
            month_span:"/mesečno",
            basic_text:"OSNOVNI",
            basic_card_fact1:"Besplatne mesečne nadogradnje",
            basic_card_fact2:"Održavanje servera",
            basic_card_fact3:"Besplatan hosting",
            basic_card_fact4:"Besplatan domen",
            basic_card_fact5:"Optimizacija",
            basic_card_fact6:"24h podrška",
            advanced:"NAPREDNI",
            advanced_fact1:"Održavanje baze podataka",
            advanced_fact2:"Backup baze svakih sedam dana",
            advanced_fact3:"Besplatne mesečne nadogradnje",
            advanced_fact4:"3 veće nadogradnje",
            advanced_fact5:"Optimizacija",
            advanced_fact6:"24h podrska",
            pro:"PRO",
            pro_fact1:"Odrzavanje baze podataka",
            pro_fact2:"Dnevni backup",
            pro_fact3:"Sve nadogradnje besplatne",
            pro_fact4:"Napredni hosting",
            pro_fact5:"Google reklame",
            pro_fact6:"24h podrška",
            contact_us_fm:"Kontaktirajte nas za više",
            contact_us:"Kontaktirajte nas",
            web_app_header:"Karakteristike veb aplikacije",
            encryption:"Enkripcija",
            performance:"Performanse",
            responsive:"Prilagodljivost",
            admin_panel:"Admin panel",
            encryption_text:"Svi pristupni podaci su enkriptovani",
            peformance_text:"Minimalno vreme učitavanje stranice",
            responsive_text:"Veb stranice prilagođene svim rezolucijama",
            admin_panel_text:"Kreiranje admin panela u skladu sa Vašim zeljama",
            order_first_header:"Poruči svoj sajt",
            order_second_header:"Prosledi porudzbinu",
            order_paragraf_fp:"Klikom na sledeće dugme posetite našu stranicu",
            order_paragraf_span:"na kojoj možete napraviti vašu porudzbinu,",
            order_paragraf_sp:"nakon toga ce porudzbina biti prosledjena našem admin timu koji če vas kontaktirati.",
            order_btn:"Napravi svoj sajt",
            photography_header:"Fotografije",
            photography_paragraf:"Jedna od stvari koja krasi svaki sajt jesu fotografije viskog kvaliteta. Ukoliko još uvek nemate profesionalne fotografije vaše firme,možemo Vas posetiti i uslikati Vas poslovni objekat.",
            photo_shoot:"Profesionalno slikanje",
            photo_edit:"Profesionalna obrada slika",
            photo_edit2:"Obrada slika",
            sidebar_text1:"Početna",
            sidebar_text2:"O nama",
             sidebar_text3:"Naruči",
             sidebar_text4:"Veštine",
             sidebar_text5:"Paketi održavanja",
             sidebar_text6:"Karakteristike",
             sidebar_text7:"Fotografije",
             sidebar_text8:"Kontakt",
             sidebar_text9:"Admin",
            


        }

        ,en:{
            header_big_text:"We focus on detail",
            header_underline_text:"Your ideas become reality",
            header_btn:"More information",
            four_card_h1:"Be a professional",
            four_card_paragraf_fp:"Stay up-to-date and",
            four_card_paragraf_span:" grow your business ",
            four_card_paragraf_sp:"with a professional website",
            code_card_fp:"Using the latest technologies",
            code_card_sp:"when creating products",
            modern_design_card:"Creating unique modern design websites",
            relationship_card:"Superior customer relationships",
            production_card_fp:"Production of your",
            production_card_sp:" projects in record time",
            about_div:"about.",
            about_paragraf_fp:"We are a team of professionals working on",
            about_paragraf_span1:" web application development,",
            about_paragraf_span2:"presentation sites",
            about_paragraf_sp:"and other IT services.",
            about_paragraf_tp:" You can find more information on our About Us page",
            about_div_btn:"About more",
            skill_header:"skill",
            pricing_header:"Maintenance packages",
            pricing_paragraf_fp:"In order for your site to function properly and to be",
            pricing_paragraf_span:" well positioned",
            pricing_paragraf_sp:"it is necessary to constantly work on it, ie it needs response.",
            month_span:"/month",
            basic_text:"BASIC",
            basic_card_fact1:"Free small monthly updates",
            basic_card_fact2:"Maintenance server",
            basic_card_fact3:"Hosting free",
            basic_card_fact4:"Domain free",
            basic_card_fact5:"Optimization",
            basic_card_fact6:"24h support",
            advanced:"ADVANCED",
            advanced_fact1:"Maintenance database",
            advanced_fact2:"Backup every seven days",
            advanced_fact3:"Free small monthly updates",
            advanced_fact4:"3 big updates",
            advanced_fact5:"Optimization",
            advanced_fact6:"24h support",
            pro:"PRO",
            pro_fact1:"Maintenance database",
            pro_fact2:"Daily backup",
            pro_fact3:"All updates free",
            pro_fact4:"Better hosting",
            pro_fact5:"Google Ads",
            pro_fact6:"24h support",
            contact_us_fm:"Contact us for more",
            contact_us:"Contact us",
            web_app_header:"Characteristics Web Application",
            encryption:"Encryption",
            performance:"Performance",
            responsive:"Responsive",
            admin_panel:"Admin panel",
            encryption_text:"All user access data is encrypted",
            peformance_text:"Minimum page load time on access",
            responsive_text:"Website tailored to all screen resolutions",
            admin_panel_text:"Create an admin panel to suit your needs",
            order_first_header:"MAKE YOUR WEBSITE",
            order_second_header:"PLACE YOUR ORDER",
            order_paragraf_fp:"Click on the following button to visit our site",
            order_paragraf_span:"where you can place your order",
            order_paragraf_sp:"after which the order will be forwarded to our admin team who will contact you.",
            order_btn:"Make a website",
            photography_header:"PHOTOGRAPHY",
            photography_paragraf:"One of the things that adorns each site are high quality photos. If you still do not have professional photos of your company, he can visit you and make a photo",
            photo_shoot:"Professional photography",
            photo_edit:"Professional image editing",
            photo_edit2:"Photo editing",
            sidebar_text1:"Home",
            sidebar_text2:"About",
            sidebar_text3:"Order",
            sidebar_text4:"Skill",
            sidebar_text5:"Pricing table",
            sidebar_text6:"Characteristics",
            sidebar_text7:"Photography",
            sidebar_text8:"Contact Form",
            sidebar_text9:"Admin",
           


        }}

    ]
}