export class OrderTranslate{
    
    static languagesWords:Array<any>=[
       
        {sr:{
            steper_one:"Lični Podaci",
            steper_two:"Opis Sajta",
            steper_three:"Završeno",
            field1_steper_one:"Ime",
            placeholder_field1:"Unesite vaše ime",
            field2_steper_one:"Prezime",
            placeholder_field2:"Unesite vaše prezime",
            field3_steper_one:"E-mail",
            placeholder_field3:"Unesite vaš e-mail",
            field4_steper_one:"Važeća e-mail adresa",
            field5_steper_one:"Kontakt Telefon",
            placeholder_field4:"Unesite vaš telefon",
            field6_steper_one:"Važeći telefonski broj",
            field7_steper_one:"Imate ideju za vaš sajt, postavite link:",
            aaaa:"Dodajte link željenog sajta",
            text1_steper_two:"Vaš veb sajt je:",
            text2_steper_two:"Koliko stranica želite",
            text3_steper_two:"Domen",
            text4_steper_two:"Hosting",
            text5_steper_two:"Unesite željeni naziv sajta",
            text6_steper_two:"Unesite željeni naziv sajta i domen (www.alemarc.dev/com/rs/..)",
            text7_steper_two:"Da li želite kontakt formu u okviru sajta?",
            text8_steper_two:"Da, želim",
            text9_steper_two:"Da li želite mogućnost implementacije elektronske pošte u okviru sajta?",
            button_1:"Sledeće",
            button_2:"Nazad",
            button_3:"Pošalji",
            text1_steper_three:"Odaberite željeni paket",
            text2_steper_three:"Da li želite animirani sadržaj na vašem sajtu?",
            text3_steper_three:"Implementacija online plaćanja",
            text4_steper_three:"Da li želite profesionalno slikanje?",
            text5_steper_three:"Da li želite više jezika na vašem sajtu?",
            text6_steper_three:"Ostavite komentar",
            text7_steper_three:"U komentaru ispod napišite željeni jezik",
            text8_steper_three:"Odaberite vrstu",
            sidebar_text1:"Početna",
            sidebar_text2:"O nama",
             sidebar_text3:"Naruči",
             sidebar_text4:"Tehnička podrška",
             sidebar_text5:"Ko smo mi?",
             sidebar_text6:"Projekti",
             sidebar_text7:"Utisci klijenata",
             sidebar_text8:"Kontakt",
        }

        ,en:{
            steper_one:"Personal Data",
            steper_two:"Site Description",
            steper_three:"Done",
            field1_steper_one:"Name",
            placeholder_field1:"Enter your name",
            
            field2_steper_one:"Last Name",
            placeholder_field2:"Enter your last name",
            field3_steper_one:"E-mail",
            placeholder_field3:"Enter your e-mail",
            field4_steper_one:"Valid e-mail address",
            field5_steper_one:"Contact Phone",
            placeholder_field4:"Enter your phone",
            field6_steper_one:"Vaild phone number",
            field7_steper_one:"Have idea for your site, share the link:",
            aaaa:"Add the link of the site you want",
            text1_steper_two:"Your web site is:",
            text2_steper_two:"How many pages you want",
            text3_steper_two:"Domain",
            text4_steper_two:"Hosting",
            text5_steper_two:"Enter the desired website name",
            text6_steper_two:"Enter the desired website name and domain (www.alemarc.dev/com/rs/..)",
            text7_steper_two:"Do you want the contact form on your web site?",
            text8_steper_two:"Yes, I want.",
            text9_steper_two:"Do you want the ability to implement email within the site?",
            button_1:"Next",
            button_2:"Back",
            button_3:"Send",
            text1_steper_three:"Select the package you want",
            text2_steper_three:"Do you want animated content on your site?",
            text3_steper_three:"Implementation of online payments",
            text4_steper_three:"Do you want a professional photographer?",
            text5_steper_three:"Do you want more languages on your site?",
            text6_steper_three:"Leave a comment",
            text7_steper_three:"In the comment below, write the  language you want",
            text8_steper_three:"Select the type",
            sidebar_text1:"Home",
            sidebar_text2:"About",
            sidebar_text3:"Order",
            sidebar_text4:"Technical Support",
            sidebar_text5:"Who are we?",
            sidebar_text6:"Projects",
            sidebar_text7:"Impressions",
            sidebar_text8:"Contact Form",

        }}


    ]
}